export const FIXED_REGION = "REGION V (Bicol Region)";
export const FIXED_PROVINCE = "Camarines Norte";

export const CITY_BARANGAY_MAP = {
  Basud: [
    "Aguit-it", "Backong", "Bagaobawan", "Calangcawan Norte", "Calangcawan Sur",
    "Culayculay", "Dagang", "Gahonon", "Gubat Norte", "Gubat Sur", "Ignit",
    "Kaibigan", "Langa-langa", "Laniton", "Lastic", "Mabini", "Manlimonsito",
    "Matango", "Mocong", "Oloapaen", "Ombao Heights", "Ombao Tibang", "Omboy",
    "Pagsangahan", "Pambuhan", "Pinagwarasan", "Plaridel", "Poblacion",
    "Salvacion", "San Isidro", "San Roque", "Santa Rosa Norte", "Santa Rosa Sur",
    "Taba-taba", "Tacad", "Taisan", "Tambongon", "Tenerife", "Yapak",
  ],
  Capalonga: [
    "Alayao", "Binawangan", "Calabaca", "Calagbagang", "Catabaguangan",
    "Catioan", "Del Pilar", "Gilong", "Guayabo", "Lignon", "Mabini",
    "Magsaysay", "Mantalongon", "Milagrosa", "Plaridel", "Poblacion", "Quirino",
    "Roosevelt", "Salvacion", "San Antonio", "San Francisco", "San Isidro",
    "Santa Cruz", "Santa Elena", "Santa Maria", "Santo Nino", "Sinagapos",
    "Vista Hermosa",
  ],
  Daet: [
    "Alawihao", "Awitan", "Bagasbas", "Barangay I (Pob.)", "Barangay II (Pob.)",
    "Barangay III (Pob.)", "Barangay IV (Pob.)", "Barangay V (Pob.)",
    "Barangay VI (Pob.)", "Barangay VII (Pob.)", "Barangay VIII (Pob.)",
    "Bibirao", "Borabod", "Calasgasan", "Camambugan", "Cobangbang (Sto. Nino)",
    "Dogongan", "Garcia", "Gahonon", "Gubat", "Lag-on", "Lucrecia", "Magang",
    "Mancruz (San Juan)", "Pamorangon", "San Isidro",
  ],
  "Jose Panganiban": [
    "Bagong Bayan", "Calero", "Dahican", "Dayhagan", "Estacion", "Lag-on",
    "Larap", "Lorena", "Luyos", "Mabini", "Mabungabon", "Managpi",
    "Manaringon", "Mercedes", "Napaod", "Parang", "Placer", "Poblacion I",
    "Poblacion II", "Poblacion III", "Port Junction Norte", "Port Junction Sur",
    "Santa Milagrosa", "Tacay", "Tambo", "Trinidad", "Vinas", "Wawa",
  ],
  Labo: [
    "Abella", "Agusigin", "Balangcawan Norte", "Balangcawan Sur", "Balite",
    "Bautista", "Bayabas", "Bena", "Binanuahan East", "Binanuahan West",
    "Bulacan", "Caayunan", "Calibunan", "Camambugan", "Candawan", "Capalogan",
    "Catabaguangan", "Catioan", "Codon", "Colacling", "Colomio", "Corucao",
    "Del Pilar", "Gahonon", "Guadalupe", "Guinabonan", "Herrera", "Hoyohoy",
    "Imelda", "Inauayan", "J. Milan (Catanggalan)", "Kaibigan", "Lag-on",
    "Lictingtung", "Lignon", "Lumbangan", "Luna Norte", "Luna Sur", "Mabini",
    "Mabolo", "Macabug", "Magang", "Magsaysay", "Manuangan", "Maria",
    "Masalong Norte", "Masalong Sur", "Mataque", "Mercedes", "Napaod",
    "Niabonan", "Obaliw Recto", "Ocampo", "Ola Norte", "Ola Sur", "Osmena",
    "Oyon", "Pag-asa", "Palong", "Pancucuran", "Pawili", "Plaridel",
    "Poblacion", "Pola", "Pood", "Quezon", "Quirino", "Roosevelt", "Rosario",
    "Salvacion", "San Antonio Norte", "San Antonio Sur", "San Isidro",
    "San Lorenzo", "San Miguel", "San Pablo Norte", "San Pablo Sur",
    "San Patricio Norte", "San Patricio Sur", "San Ramon", "San Vicente",
    "Santa Cruz", "Sapang Palay", "Sumaoy", "Tamban", "Tulay", "Tungmalaong",
    "Vega", "Villasol",
  ],
  Mercedes: [
    "Apuao", "Barangay I (Pob.)", "Barangay II (Pob.)", "Barangay III (Pob.)",
    "Barangay IV (Pob.)", "Barangay V (Pob.)", "Barangay VI (Pob.)",
    "Barangay VII (Pob.)", "Boot", "Casagsagan", "Comadaycaday",
    "Comadogcadog", "Daculang Bolo", "Daguit", "Danao", "Guayabo", "Himanag",
    "Lagha", "Lanot", "Langon", "Libas", "Mabini", "Macolabo Island",
    "Malinis", "Maot", "Masikla", "Matnog", "Mobo", "Nacawit", "Pambuhan",
    "Patag", "Patrol", "Quinapaguian", "Salingogon", "Sirangan", "Taba",
    "Tawig", "Tugos", "Yabo",
  ],
  Paracale: [
    "Awitan", "Bagumbayan", "Bakal Norte", "Bakal Sur", "Batobalani",
    "Calaburnay", "Capacuan", "Casagsagan", "Caypandan", "Colasi", "Gahonon",
    "Guinabonan", "Jose Panganiban", "Lag-on", "Larap", "Luklukan Norte",
    "Luklukan Sur", "Mabini", "Madlawon", "Mananao", "Mancuartira",
    "Mangkasuy", "Maot", "Masalong", "Minalabac", "Nakalaya", "Norte", "Obo",
    "Pag-asa", "Pangarairan", "Penafrancia", "Poblacion", "Tabugon", "Tagas",
    "Talisay", "Tambong", "Tigbinan", "Tulay Na Lupa",
  ],
  "San Lorenzo Ruiz": [
    "Alegria", "Anahawan", "Anonang", "Bagong Silang", "Calangcawan",
    "Guinabonan", "Iligan", "Inductan", "Km. 891 Pob. (Tulay)", "Lamon",
    "Mabilo I", "Mabilo II", "Nakalaya", "Northern Poblacion", "Placer",
    "Salvacion", "San Antonio", "San Francisco", "San Isidro", "San Jose",
    "San Martin", "San Pedro", "Santa Cruz", "Santa Elena", "Santiago",
    "Southern Poblacion", "Talahib", "Talisay", "Tamban", "Tambo", "Tandoc",
    "Tison",
  ],
  "San Vicente": [
    "Bugtong na Pulo", "Calwit", "Labnig", "Mabini", "Madlawon", "Pag-asa",
    "Poblacion", "San Antonio", "San Francisco", "San Isidro", "San Ramon",
    "Santa Cruz", "Santa Elena", "Santo Nino", "Taguilid",
  ],
  "Santa Elena": [
    "Angga", "Bactas", "Binanwaanan", "Bulhao", "Busak", "Caawigan",
    "Caayunan", "Calabaca", "Calagbagang", "Calaocan", "Camambugan",
    "Candawan", "Catabaguangan", "Cataroan", "Caugmayan", "Cayucay",
    "Del Pilar", "Guadalupe", "Hawak", "Itulan", "Laniton", "Lastic",
    "Mabini", "Magsaysay", "Manlimonsito", "Matango", "Mocong", "Oloapaen",
    "Pagsangahan", "Pambuhan", "Pinagwarasan", "Plaridel", "Poblacion",
    "Puro", "Salvacion", "San Antonio", "San Francisco", "San Isidro",
    "San Jose", "San Martin", "San Miguel", "San Pedro", "San Ramon",
    "San Roque", "Santa Cruz", "Santa Elena", "Santo Nino", "Tacad", "Taisan",
    "Talisay", "Tambongon", "Tenerife",
  ],
  Talisay: [
    "Bagong Bayan", "Bautista", "Calasag", "Catagbacan", "Codon", "Hampas",
    "Laniton", "Limaong", "Mabini", "Magang", "Mataque", "Maugat East",
    "Maugat West", "Pag-asa", "Poblacion", "Salvacion", "San Antonio",
    "San Isidro", "San Jose", "San Miguel", "San Pablo", "San Roque",
    "Santa Cruz", "Santo Nino", "Tapihan", "Tulatula",
  ],
  Vinzons: [
    "Alaban", "Algaran", "Balagba", "Binobong", "Burabod", "Cagbanaba",
    "Calabagas", "Calangcawan Norte", "Calangcawan Sur", "Cawayan Pola",
    "Cawayan Sapa", "Colasi", "Del Pilar", "Gubat Norte", "Gubat Sur",
    "Himaao", "Indangan", "La Purisima", "Labo", "Laga", "Mabini",
    "Masalong", "Maulawin", "Nakalaya", "Pag-asa", "Pambuhan", "Pinit",
    "Pob. I (Barangay I)", "Pob. II (Barangay II)", "Pob. III (Barangay III)",
    "Pob. IV (Barangay IV)", "Potot", "Sabang", "Salvacion", "San Antonio",
    "San Francisco", "San Isidro", "San Jose", "San Pascual", "Santa Cruz",
    "Santo Nino", "Taisan", "Tambongon", "Tulay Na Lupa",
  ],
  "Tulay Na Lupa": [
    "Calabasa", "Mabini", "Pag-asa (Pob.)", "Poblacion", "San Antonio",
    "San Francisco", "San Isidro", "San Jose", "Santa Cruz", "Santa Elena",
    "Santo Nino", "Villa Aurora", "Villa Hermosa",
  ],
};

export const CITIES = Object.keys(CITY_BARANGAY_MAP).sort();
